services:
  db:
    image: postgres:16
    container_name: postgres_16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5428:5432"
    volumes:
      - postgres_data16:/var/lib/postgresql/data16
  
volumes:
  postgres_data16:
